export { default as Menu } from './Menu'
export { default as IPList } from './IPList'
export { default as Game } from './Game'
export { default as Preloader } from './Preloader'
export { default as Instruments } from './Instruments'
export { default as Info } from './Info'
